### ISSUE TITLE
How to hex-encode block_chain_ids ?

### ISSUE THREAD

**Issue by ijonas** [ava-labs/subnet-vrf-contracts#4]
Hi there,

I'm trying to deploy the example and I'm stuck generating the correct .env file - specifically I can't figure out how to "hex-encode" a blockchain id. 

For example: Fuji C-Chain's blockchain ID is "yH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp" as per the details on https://subnets-test.avax.network/c-chain.

How do I convert blockchain-id so that it fits into an `address` value that is passed into the contructor for the VRFProvider or VRFProxy ?

Many thanks!

**Comment by geoff-vball** [comment]
Hey! Our IDs are encoded in `cb58`. Here's a tool that will let you do the conversion! https://avatools.io/

The output you should get is `7fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5`

Note that the correct type for `blockchain-id` is `bytes32`, not `address`.
